"""One-time wallet setup for Polymarket trading.

Generates an Ethereum private key, derives Polymarket API credentials,
and appends the keys to .env so the agent can trade.

Usage:
    cd agent && uv run python setup_wallet.py

Note: Must be run with `uv run` from the agent/ directory to use the
project's virtual environment where eth_account is installed.
"""

import os
import sys

from dotenv import load_dotenv
from eth_account import Account

ENV_PATH = os.path.join(os.path.dirname(__file__), "..", ".env")
load_dotenv(ENV_PATH)


def main():
    # Check if already configured
    if os.getenv("POLYMARKET_PRIVATE_KEY"):
        print("Wallet already configured in .env")
        print(f"  Address: {Account.from_key(os.getenv('POLYMARKET_PRIVATE_KEY')).address}")
        print("\nTo generate a new wallet, remove POLYMARKET_PRIVATE_KEY from .env first.")
        sys.exit(0)

    # Generate new Ethereum account
    acct = Account.create()
    private_key = acct.key.hex()
    address = acct.address

    print("=" * 60)
    print("  Miss Fortune — Wallet Setup")
    print("=" * 60)
    print()
    print(f"  Address:     {address}")
    print(f"  Private Key: {private_key}")
    print()

    # Derive Polymarket API credentials
    print("Deriving Polymarket API credentials...")
    try:
        from py_clob_client.client import ClobClient

        temp_client = ClobClient(
            "https://clob.polymarket.com",
            key=private_key,
            chain_id=137,
        )
        creds = temp_client.create_or_derive_api_creds()
        print("  API credentials derived successfully.")
        print(f"  API Key: {creds.api_key[:12]}...")
    except Exception as e:
        print(f"  Warning: Could not derive API creds: {e}")
        print("  You can still add the keys to .env — creds will be derived at startup.")

    # Append to .env
    with open(ENV_PATH, "a") as f:
        f.write(f"\n# Polymarket wallet (generated by setup_wallet.py)\n")
        f.write(f"POLYMARKET_PRIVATE_KEY={private_key}\n")
        f.write(f"POLYMARKET_FUNDER_ADDRESS={address}\n")

    print()
    print("Keys written to .env")
    print()
    print("=" * 60)
    print("  Next Steps")
    print("=" * 60)
    print()
    print(f"  1. Fund your wallet with USDC on Polygon:")
    print(f"     Send USDC (Polygon) to: {address}")
    print()
    print(f"  2. You also need a small amount of MATIC for gas fees.")
    print()
    print(f"  3. Approve the Polymarket CTF Exchange contract to spend your USDC.")
    print(f"     The agent will handle this automatically on the first trade,")
    print(f"     or you can approve manually via Polygonscan.")
    print()
    print(f"  4. Restart the agent to activate trading:")
    print(f"     cd agent && uv run uvicorn main:app --reload")
    print()


if __name__ == "__main__":
    main()
